###############################################################
# templates/service.yaml
###############################################################
{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
  namespace: {{ $.Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $svc.containerPort }}
      targetPort: {{ $svc.containerPort }}
      nodePort: {{ $svc.nodePort }}
{{- end }}